<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CtlDistritoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $distritos = [
            ['id' => 1, 'nombre' => 'Ahuachapán', 'municipio_id' => 2, 'codigo' => '01'],
            ['id' => 2, 'nombre' => 'Apaneca', 'municipio_id' => 2, 'codigo' => '02'],
            ['id' => 3, 'nombre' => 'Atiquizaya', 'municipio_id' => 1, 'codigo' => '03'],
            ['id' => 4, 'nombre' => 'Concepción De Ataco', 'municipio_id' => 2, 'codigo' => '04'],
            ['id' => 5, 'nombre' => 'El Refugio', 'municipio_id' => 1, 'codigo' => '05'],
            ['id' => 6, 'nombre' => 'Guaymango', 'municipio_id' => 3, 'codigo' => '06'],
            ['id' => 7, 'nombre' => 'Jujutla', 'municipio_id' => 3, 'codigo' => '07'],
            ['id' => 8, 'nombre' => 'San Francisco Menéndez', 'municipio_id' => 3, 'codigo' => '08'],
            ['id' => 9, 'nombre' => 'San Lorenzo', 'municipio_id' => 1, 'codigo' => '09'],
            ['id' => 10, 'nombre' => 'San Pedro Puxtla', 'municipio_id' => 3, 'codigo' => '10'],
            ['id' => 11, 'nombre' => 'Tacuba', 'municipio_id' => 2, 'codigo' => '11'],
            ['id' => 12, 'nombre' => 'Turín', 'municipio_id' => 1, 'codigo' => '12'],
            ['id' => 13, 'nombre' => 'Candelaria De La Frontera', 'municipio_id' => 4, 'codigo' => '01'],
            ['id' => 14, 'nombre' => 'Coatepeque', 'municipio_id' => 5, 'codigo' => '02'],
            ['id' => 15, 'nombre' => 'Chalchuapa', 'municipio_id' => 4, 'codigo' => '03'],
            ['id' => 16, 'nombre' => 'El Congo', 'municipio_id' => 5, 'codigo' => '04'],
            ['id' => 17, 'nombre' => 'El Porvenir', 'municipio_id' => 4, 'codigo' => '05'],
            ['id' => 18, 'nombre' => 'Masahuat', 'municipio_id' => 6, 'codigo' => '06'],
            ['id' => 19, 'nombre' => 'Metapán', 'municipio_id' => 6, 'codigo' => '07'],
            ['id' => 20, 'nombre' => 'San Antonio Pajonal', 'municipio_id' => 4, 'codigo' => '08'],
            ['id' => 21, 'nombre' => 'San Sebastián Salitrillo', 'municipio_id' => 4, 'codigo' => '09'],
            ['id' => 22, 'nombre' => 'Santa Ana', 'municipio_id' => 7, 'codigo' => '10'],
            ['id' => 23, 'nombre' => 'Santa Rosa Guachipilin', 'municipio_id' => 6, 'codigo' => '11'],
            ['id' => 24, 'nombre' => 'Santiago de la Frontera', 'municipio_id' => 4, 'codigo' => '12'],
            ['id' => 25, 'nombre' => 'Texistepeque', 'municipio_id' => 6, 'codigo' => '13'],
            ['id' => 26, 'nombre' => 'Acajutla', 'municipio_id' => 11, 'codigo' => '01'],
            ['id' => 27, 'nombre' => 'Armenia', 'municipio_id' => 10, 'codigo' => '02'],
            ['id' => 28, 'nombre' => 'Caluco', 'municipio_id' => 10, 'codigo' => '03'],
            ['id' => 29, 'nombre' => 'Cuisnahuat', 'municipio_id' => 10, 'codigo' => '04'],
            ['id' => 30, 'nombre' => 'Santa Isabel Ishuatan', 'municipio_id' => 10, 'codigo' => '05'],
            ['id' => 31, 'nombre' => 'Izalco', 'municipio_id' => 10, 'codigo' => '06'],
            ['id' => 32, 'nombre' => 'Juayúa', 'municipio_id' => 8, 'codigo' => '07'],
            ['id' => 33, 'nombre' => 'Nahuizalco', 'municipio_id' => 8, 'codigo' => '08'],
            ['id' => 34, 'nombre' => 'Nahulingo', 'municipio_id' => 9, 'codigo' => '09'],
            ['id' => 35, 'nombre' => 'Salcoatitán', 'municipio_id' => 8, 'codigo' => '10'],
            ['id' => 36, 'nombre' => 'San Antonio Del Monte', 'municipio_id' => 9, 'codigo' => '11'],
            ['id' => 37, 'nombre' => 'San Julián', 'municipio_id' => 10, 'codigo' => '12'],
            ['id' => 38, 'nombre' => 'Santa Catarina Masahuat', 'municipio_id' => 8, 'codigo' => '13'],
            ['id' => 39, 'nombre' => 'Santo Domingo Guzmán', 'municipio_id' => 9, 'codigo' => '14'],
            ['id' => 40, 'nombre' => 'Sonsonate', 'municipio_id' => 9, 'codigo' => '15'],
            ['id' => 41, 'nombre' => 'Sonzacate', 'municipio_id' => 9, 'codigo' => '16'],
            ['id' => 42, 'nombre' => 'Agua Caliente', 'municipio_id' => 13, 'codigo' => '01'],
            ['id' => 43, 'nombre' => 'Arcatao', 'municipio_id' => 14, 'codigo' => '02'],
            ['id' => 44, 'nombre' => 'Azacualpa', 'municipio_id' => 14, 'codigo' => '03'],
            ['id' => 45, 'nombre' => 'Citalá', 'municipio_id' => 12, 'codigo' => '04'],
            ['id' => 46, 'nombre' => 'Comalapa', 'municipio_id' => 14, 'codigo' => '05'],
            ['id' => 47, 'nombre' => 'Concepción Quezaltepeque', 'municipio_id' => 14, 'codigo' => '06'],
            ['id' => 48, 'nombre' => 'Chalatenango', 'municipio_id' => 14, 'codigo' => '07'],
            ['id' => 49, 'nombre' => 'Dulce Nombre de María', 'municipio_id' => 13, 'codigo' => '08'],
            ['id' => 50, 'nombre' => 'El Carrizal', 'municipio_id' => 14, 'codigo' => '09'],
            ['id' => 51, 'nombre' => 'El Paraíso', 'municipio_id' => 13, 'codigo' => '10'],
            ['id' => 52, 'nombre' => 'La Laguna', 'municipio_id' => 14, 'codigo' => '11'],
            ['id' => 53, 'nombre' => 'La Palma', 'municipio_id' => 12, 'codigo' => '12'],
            ['id' => 54, 'nombre' => 'La Reina', 'municipio_id' => 13, 'codigo' => '13'],
            ['id' => 55, 'nombre' => 'Las Vueltas', 'municipio_id' => 14, 'codigo' => '14'],
            ['id' => 56, 'nombre' => 'Nombre De Jesús', 'municipio_id' => 14, 'codigo' => '15'],
            ['id' => 57, 'nombre' => 'Nueva Concepción', 'municipio_id' => 13, 'codigo' => '16'],
            ['id' => 58, 'nombre' => 'Nueva Trinidad', 'municipio_id' => 14, 'codigo' => '17'],
            ['id' => 59, 'nombre' => 'Ojos De Agua', 'municipio_id' => 14, 'codigo' => '18'],
            ['id' => 60, 'nombre' => 'Potonico', 'municipio_id' => 14, 'codigo' => '19'],
            ['id' => 61, 'nombre' => 'San Antonio de La Cruz', 'municipio_id' => 14, 'codigo' => '20'],
            ['id' => 62, 'nombre' => 'San Antonio Ranchos', 'municipio_id' => 14, 'codigo' => '21'],
            ['id' => 63, 'nombre' => 'San Fernando', 'municipio_id' => 13, 'codigo' => '22'],
            ['id' => 64, 'nombre' => 'San Francisco Lempa', 'municipio_id' => 14, 'codigo' => '23'],
            ['id' => 65, 'nombre' => 'San Francisco Morazán', 'municipio_id' => 13, 'codigo' => '24'],
            ['id' => 66, 'nombre' => 'San Ignacio', 'municipio_id' => 12, 'codigo' => '25'],
            ['id' => 67, 'nombre' => 'San Isidro Labrador', 'municipio_id' => 14, 'codigo' => '26'],
            ['id' => 68, 'nombre' => 'San José Cancasque', 'municipio_id' => 14, 'codigo' => '27'],
            ['id' => 69, 'nombre' => 'San José Flores', 'municipio_id' => 14, 'codigo' => '28'],
            ['id' => 70, 'nombre' => 'San Luis Carmen', 'municipio_id' => 14, 'codigo' => '29'],
            ['id' => 71, 'nombre' => 'San Miguel Mercedes', 'municipio_id' => 14, 'codigo' => '30'],
            ['id' => 72, 'nombre' => 'San Rafael', 'municipio_id' => 13, 'codigo' => '31'],
            ['id' => 73, 'nombre' => 'Santa Rita', 'municipio_id' => 13, 'codigo' => '32'],
            ['id' => 74, 'nombre' => 'Tejutla', 'municipio_id' => 13, 'codigo' => '33'],
            ['id' => 75, 'nombre' => 'Antiguo Cuscatlán', 'municipio_id' => 18, 'codigo' => '01'],
            ['id' => 76, 'nombre' => 'Ciudad Arce', 'municipio_id' => 16, 'codigo' => '02'],
            ['id' => 77, 'nombre' => 'Colón', 'municipio_id' => 17, 'codigo' => '03'],
            ['id' => 78, 'nombre' => 'Comasagua', 'municipio_id' => 20, 'codigo' => '04'],
            ['id' => 79, 'nombre' => 'Chiltiupan', 'municipio_id' => 19, 'codigo' => '05'],
            ['id' => 80, 'nombre' => 'Huizúcar', 'municipio_id' => 18, 'codigo' => '06'],
            ['id' => 81, 'nombre' => 'Jayaque', 'municipio_id' => 17, 'codigo' => '07'],
            ['id' => 82, 'nombre' => 'Jicalapa', 'municipio_id' => 19, 'codigo' => '08'],
            ['id' => 83, 'nombre' => 'La Libertad', 'municipio_id' => 19, 'codigo' => '09'],
            ['id' => 84, 'nombre' => 'Nuevo Cuscatlán', 'municipio_id' => 18, 'codigo' => '10'],
            ['id' => 85, 'nombre' => 'Santa Tecla', 'municipio_id' => 20, 'codigo' => '11'],
            ['id' => 86, 'nombre' => 'Quezaltepeque', 'municipio_id' => 15, 'codigo' => '12'],
            ['id' => 87, 'nombre' => 'Sacacoyo', 'municipio_id' => 17, 'codigo' => '13'],
            ['id' => 88, 'nombre' => 'San José Villanueva', 'municipio_id' => 18, 'codigo' => '14'],
            ['id' => 89, 'nombre' => 'San Juan Opico', 'municipio_id' => 16, 'codigo' => '15'],
            ['id' => 90, 'nombre' => 'San Matías', 'municipio_id' => 15, 'codigo' => '16'],
            ['id' => 91, 'nombre' => 'San Pablo Tacachico', 'municipio_id' => 15, 'codigo' => '17'],
            ['id' => 92, 'nombre' => 'Tamanique', 'municipio_id' => 19, 'codigo' => '18'],
            ['id' => 93, 'nombre' => 'Talnique', 'municipio_id' => 17, 'codigo' => '19'],
            ['id' => 94, 'nombre' => 'Teotepeque', 'municipio_id' => 19, 'codigo' => '20'],
            ['id' => 95, 'nombre' => 'Tepecoyo', 'municipio_id' => 17, 'codigo' => '21'],
            ['id' => 96, 'nombre' => 'Zaragoza', 'municipio_id' => 18, 'codigo' => '22'],
            ['id' => 97, 'nombre' => 'Aguilares', 'municipio_id' => 21, 'codigo' => '01'],
            ['id' => 98, 'nombre' => 'Apopa', 'municipio_id' => 22, 'codigo' => '02'],
            ['id' => 99, 'nombre' => 'Ayutuxtepeque', 'municipio_id' => 24, 'codigo' => '03'],
            ['id' => 100, 'nombre' => 'Cuscatancingo', 'municipio_id' => 23, 'codigo' => '04'],
            ['id' => 101, 'nombre' => 'El Paisnal', 'municipio_id' => 21, 'codigo' => '05'],
            ['id' => 102, 'nombre' => 'Guazapa', 'municipio_id' => 21, 'codigo' => '06'],
            ['id' => 103, 'nombre' => 'Ilopango', 'municipio_id' => 23, 'codigo' => '07'],
            ['id' => 104, 'nombre' => 'Mejicanos', 'municipio_id' => 24, 'codigo' => '08'],
            ['id' => 105, 'nombre' => 'Nejapa', 'municipio_id' => 22, 'codigo' => '09'],
            ['id' => 106, 'nombre' => 'Panchimalco', 'municipio_id' => 25, 'codigo' => '10'],
            ['id' => 107, 'nombre' => 'Rosario De Mora', 'municipio_id' => 25, 'codigo' => '11'],
            ['id' => 108, 'nombre' => 'San Marcos', 'municipio_id' => 24, 'codigo' => '12'],
            ['id' => 109, 'nombre' => 'San Martin', 'municipio_id' => 23, 'codigo' => '13'],
            ['id' => 110, 'nombre' => 'San Salvador', 'municipio_id' => 24, 'codigo' => '14'],
            ['id' => 111, 'nombre' => 'Santiago Texacuangos', 'municipio_id' => 24, 'codigo' => '15'],
            ['id' => 112, 'nombre' => 'Santo Tomas', 'municipio_id' => 24, 'codigo' => '16'],
            ['id' => 113, 'nombre' => 'Soyapango', 'municipio_id' => 23, 'codigo' => '17'],
            ['id' => 114, 'nombre' => 'Tonacatepeque', 'municipio_id' => 23, 'codigo' => '18'],
            ['id' => 115, 'nombre' => 'Ciudad Delgado', 'municipio_id' => 23, 'codigo' => '19'],
            ['id' => 116, 'nombre' => 'Candelaria', 'municipio_id' => 27, 'codigo' => '01'],
            ['id' => 117, 'nombre' => 'Cojutepeque', 'municipio_id' => 27, 'codigo' => '02'],
            ['id' => 118, 'nombre' => 'El Carmen', 'municipio_id' => 27, 'codigo' => '03'],
            ['id' => 119, 'nombre' => 'El Rosario', 'municipio_id' => 27, 'codigo' => '04'],
            ['id' => 120, 'nombre' => 'Monte San Juan', 'municipio_id' => 27, 'codigo' => '05'],
            ['id' => 121, 'nombre' => 'Oratorio de Concepción', 'municipio_id' => 26, 'codigo' => '06'],
            ['id' => 122, 'nombre' => 'San Bartolomé Perulapia', 'municipio_id' => 26, 'codigo' => '07'],
            ['id' => 123, 'nombre' => 'San Cristóbal', 'municipio_id' => 27, 'codigo' => '08'],
            ['id' => 124, 'nombre' => 'San José Guayabal', 'municipio_id' => 26, 'codigo' => '09'],
            ['id' => 125, 'nombre' => 'San Pedro Perulapán', 'municipio_id' => 26, 'codigo' => '10'],
            ['id' => 126, 'nombre' => 'San Rafael Cedros', 'municipio_id' => 27, 'codigo' => '11'],
            ['id' => 127, 'nombre' => 'San Ramón', 'municipio_id' => 27, 'codigo' => '12'],
            ['id' => 128, 'nombre' => 'Santa Cruz Analquito', 'municipio_id' => 27, 'codigo' => '13'],
            ['id' => 129, 'nombre' => 'Santa Cruz Michapa', 'municipio_id' => 27, 'codigo' => '14'],
            ['id' => 130, 'nombre' => 'Suchitoto', 'municipio_id' => 26, 'codigo' => '15'],
            ['id' => 131, 'nombre' => 'Tenancingo', 'municipio_id' => 27, 'codigo' => '16'],
            ['id' => 132, 'nombre' => 'Cuyultitán', 'municipio_id' => 30, 'codigo' => '01'],
            ['id' => 133, 'nombre' => 'El Rosario', 'municipio_id' => 29, 'codigo' => '02'],
            ['id' => 134, 'nombre' => 'Jerusalén', 'municipio_id' => 29, 'codigo' => '03'],
            ['id' => 135, 'nombre' => 'Merced La Ceiba', 'municipio_id' => 29, 'codigo' => '04'],
            ['id' => 136, 'nombre' => 'Olocuilta', 'municipio_id' => 30, 'codigo' => '05'],
            ['id' => 137, 'nombre' => 'Paraíso Osorio', 'municipio_id' => 29, 'codigo' => '06'],
            ['id' => 138, 'nombre' => 'San Antonio Masahuat', 'municipio_id' => 29, 'codigo' => '07'],
            ['id' => 139, 'nombre' => 'San Emigdio', 'municipio_id' => 29, 'codigo' => '08'],
            ['id' => 140, 'nombre' => 'San Francisco Chinameca', 'municipio_id' => 30, 'codigo' => '09'],
            ['id' => 141, 'nombre' => 'San Juan Nonualco', 'municipio_id' => 28, 'codigo' => '10'],
            ['id' => 142, 'nombre' => 'San Juan Talpa', 'municipio_id' => 30, 'codigo' => '11'],
            ['id' => 143, 'nombre' => 'San Juan Tepezontes', 'municipio_id' => 29, 'codigo' => '12'],
            ['id' => 144, 'nombre' => 'San Luis Talpa', 'municipio_id' => 30, 'codigo' => '13'],
            ['id' => 145, 'nombre' => 'San Miguel Tepezontes', 'municipio_id' => 29, 'codigo' => '14'],
            ['id' => 146, 'nombre' => 'San Pedro Masahuat', 'municipio_id' => 30, 'codigo' => '15'],
            ['id' => 147, 'nombre' => 'San Pedro Nonualco', 'municipio_id' => 29, 'codigo' => '16'],
            ['id' => 148, 'nombre' => 'San Rafael Obrajuelo', 'municipio_id' => 28, 'codigo' => '17'],
            ['id' => 149, 'nombre' => 'Santa María Ostuma', 'municipio_id' => 29, 'codigo' => '18'],
            ['id' => 150, 'nombre' => 'Santiago Nonualco', 'municipio_id' => 29, 'codigo' => '19'],
            ['id' => 151, 'nombre' => 'Tapalhuaca', 'municipio_id' => 30, 'codigo' => '20'],
            ['id' => 152, 'nombre' => 'Zacatecoluca', 'municipio_id' => 28, 'codigo' => '21'],
            ['id' => 153, 'nombre' => 'San Luis La Herradura', 'municipio_id' => 29, 'codigo' => '22'],
            ['id' => 154, 'nombre' => 'Cinquera', 'municipio_id' => 31, 'codigo' => '01'],
            ['id' => 155, 'nombre' => 'Guacotecti', 'municipio_id' => 32, 'codigo' => '02'],
            ['id' => 156, 'nombre' => 'Ilobasco', 'municipio_id' => 31, 'codigo' => '03'],
            ['id' => 157, 'nombre' => 'Jutiapa', 'municipio_id' => 31, 'codigo' => '04'],
            ['id' => 158, 'nombre' => 'San Isidro', 'municipio_id' => 32, 'codigo' => '05'],
            ['id' => 159, 'nombre' => 'Sensuntepeque', 'municipio_id' => 32, 'codigo' => '06'],
            ['id' => 160, 'nombre' => 'Tejutepeque', 'municipio_id' => 31, 'codigo' => '07'],
            ['id' => 161, 'nombre' => 'Victoria', 'municipio_id' => 32, 'codigo' => '08'],
            ['id' => 162, 'nombre' => 'Dolores', 'municipio_id' => 32, 'codigo' => '09'],
            ['id' => 163, 'nombre' => 'Apastepeque', 'municipio_id' => 33, 'codigo' => '01'],
            ['id' => 164, 'nombre' => 'Guadalupe', 'municipio_id' => 34, 'codigo' => '02'],
            ['id' => 165, 'nombre' => 'San Cayetano Istepeque', 'municipio_id' => 34, 'codigo' => '03'],
            ['id' => 166, 'nombre' => 'Santa Clara', 'municipio_id' => 33, 'codigo' => '04'],
            ['id' => 167, 'nombre' => 'Santo Domingo', 'municipio_id' => 33, 'codigo' => '05'],
            ['id' => 168, 'nombre' => 'San Esteban Catarina', 'municipio_id' => 33, 'codigo' => '06'],
            ['id' => 169, 'nombre' => 'San Ildefonso', 'municipio_id' => 33, 'codigo' => '07'],
            ['id' => 170, 'nombre' => 'San Lorenzo', 'municipio_id' => 33, 'codigo' => '08'],
            ['id' => 171, 'nombre' => 'San Sebastián', 'municipio_id' => 33, 'codigo' => '09'],
            ['id' => 172, 'nombre' => 'San Vicente', 'municipio_id' => 34, 'codigo' => '10'],
            ['id' => 173, 'nombre' => 'Tecoluca', 'municipio_id' => 34, 'codigo' => '11'],
            ['id' => 174, 'nombre' => 'Tepetitán', 'municipio_id' => 34, 'codigo' => '12'],
            ['id' => 175, 'nombre' => 'Verapaz', 'municipio_id' => 34, 'codigo' => '13'],
            ['id' => 176, 'nombre' => 'Alegría', 'municipio_id' => 35, 'codigo' => '01'],
            ['id' => 177, 'nombre' => 'Berlín', 'municipio_id' => 35, 'codigo' => '02'],
            ['id' => 178, 'nombre' => 'California', 'municipio_id' => 36, 'codigo' => '03'],
            ['id' => 179, 'nombre' => 'Concepción Batres', 'municipio_id' => 36, 'codigo' => '04'],
            ['id' => 180, 'nombre' => 'El Triunfo', 'municipio_id' => 35, 'codigo' => '05'],
            ['id' => 181, 'nombre' => 'Ereguayquín', 'municipio_id' => 36, 'codigo' => '06'],
            ['id' => 182, 'nombre' => 'Estanzuelas', 'municipio_id' => 35, 'codigo' => '07'],
            ['id' => 183, 'nombre' => 'Jiquilisco', 'municipio_id' => 37, 'codigo' => '08'],
            ['id' => 184, 'nombre' => 'Jucuapa', 'municipio_id' => 35, 'codigo' => '09'],
            ['id' => 185, 'nombre' => 'Jucuarán', 'municipio_id' => 36, 'codigo' => '10'],
            ['id' => 186, 'nombre' => 'Mercedes Umaña', 'municipio_id' => 35, 'codigo' => '11'],
            ['id' => 187, 'nombre' => 'Nueva Granada', 'municipio_id' => 35, 'codigo' => '12'],
            ['id' => 188, 'nombre' => 'Ozatlán', 'municipio_id' => 36, 'codigo' => '13'],
            ['id' => 189, 'nombre' => 'Puerto El Triunfo', 'municipio_id' => 37, 'codigo' => '14'],
            ['id' => 190, 'nombre' => 'San Agustín', 'municipio_id' => 37, 'codigo' => '15'],
            ['id' => 191, 'nombre' => 'San Buenaventura', 'municipio_id' => 35, 'codigo' => '16'],
            ['id' => 192, 'nombre' => 'San Dionisio', 'municipio_id' => 36, 'codigo' => '17'],
            ['id' => 193, 'nombre' => 'Santa Elena', 'municipio_id' => 36, 'codigo' => '18'],
            ['id' => 194, 'nombre' => 'San Francisco Javier', 'municipio_id' => 37, 'codigo' => '19'],
            ['id' => 195, 'nombre' => 'Santa María', 'municipio_id' => 36, 'codigo' => '20'],
            ['id' => 196, 'nombre' => 'Santiago De María', 'municipio_id' => 35, 'codigo' => '21'],
            ['id' => 197, 'nombre' => 'Tecapán', 'municipio_id' => 36, 'codigo' => '22'],
            ['id' => 198, 'nombre' => 'Usulután', 'municipio_id' => 36, 'codigo' => '23'],
            ['id' => 199, 'nombre' => 'Carolina', 'municipio_id' => 38, 'codigo' => '01'],
            ['id' => 200, 'nombre' => 'Ciudad Barrios', 'municipio_id' => 38, 'codigo' => '02'],
            ['id' => 201, 'nombre' => 'Comacarán', 'municipio_id' => 39, 'codigo' => '03'],
            ['id' => 202, 'nombre' => 'Chapeltique', 'municipio_id' => 38, 'codigo' => '04'],
            ['id' => 203, 'nombre' => 'Chinameca', 'municipio_id' => 40, 'codigo' => '05'],
            ['id' => 204, 'nombre' => 'Chirilagua', 'municipio_id' => 39, 'codigo' => '06'],
            ['id' => 205, 'nombre' => 'El Transito', 'municipio_id' => 40, 'codigo' => '07'],
            ['id' => 206, 'nombre' => 'Lolotique', 'municipio_id' => 40, 'codigo' => '08'],
            ['id' => 207, 'nombre' => 'Moncagua', 'municipio_id' => 39, 'codigo' => '09'],
            ['id' => 208, 'nombre' => 'Nueva Guadalupe', 'municipio_id' => 40, 'codigo' => '10'],
            ['id' => 209, 'nombre' => 'Nuevo Edén De San Juan', 'municipio_id' => 38, 'codigo' => '11'],
            ['id' => 210, 'nombre' => 'Quelepa', 'municipio_id' => 39, 'codigo' => '12'],
            ['id' => 211, 'nombre' => 'San Antonio Del Mosco', 'municipio_id' => 38, 'codigo' => '13'],
            ['id' => 212, 'nombre' => 'San Gerardo', 'municipio_id' => 38, 'codigo' => '14'],
            ['id' => 213, 'nombre' => 'San Jorge', 'municipio_id' => 40, 'codigo' => '15'],
            ['id' => 214, 'nombre' => 'San Luis De La Reina', 'municipio_id' => 38, 'codigo' => '16'],
            ['id' => 215, 'nombre' => 'San Miguel', 'municipio_id' => 39, 'codigo' => '17'],
            ['id' => 216, 'nombre' => 'San Rafael Oriente', 'municipio_id' => 40, 'codigo' => '18'],
            ['id' => 217, 'nombre' => 'Sesori', 'municipio_id' => 38, 'codigo' => '19'],
            ['id' => 218, 'nombre' => 'Uluazapa', 'municipio_id' => 39, 'codigo' => '20'],
            ['id' => 219, 'nombre' => 'Arambala', 'municipio_id' => 41, 'codigo' => '01'],
            ['id' => 220, 'nombre' => 'Cacaopera', 'municipio_id' => 41, 'codigo' => '02'],
            ['id' => 221, 'nombre' => 'Corinto', 'municipio_id' => 41, 'codigo' => '03'],
            ['id' => 222, 'nombre' => 'Chilanga', 'municipio_id' => 42, 'codigo' => '04'],
            ['id' => 223, 'nombre' => 'Delicias De La Concepción', 'municipio_id' => 42, 'codigo' => '05'],
            ['id' => 224, 'nombre' => 'El Divisadero', 'municipio_id' => 42, 'codigo' => '06'],
            ['id' => 225, 'nombre' => 'El Rosario', 'municipio_id' => 41, 'codigo' => '07'],
            ['id' => 226, 'nombre' => 'Gualococti', 'municipio_id' => 42, 'codigo' => '08'],
            ['id' => 227, 'nombre' => 'Guatajiagua', 'municipio_id' => 42, 'codigo' => '09'],
            ['id' => 228, 'nombre' => 'Joateca', 'municipio_id' => 41, 'codigo' => '10'],
            ['id' => 229, 'nombre' => 'Jocoaitique', 'municipio_id' => 41, 'codigo' => '11'],
            ['id' => 230, 'nombre' => 'Jocoro', 'municipio_id' => 42, 'codigo' => '12'],
            ['id' => 231, 'nombre' => 'Lolotiquillo', 'municipio_id' => 42, 'codigo' => '13'],
            ['id' => 232, 'nombre' => 'Meanguera', 'municipio_id' => 41, 'codigo' => '14'],
            ['id' => 233, 'nombre' => 'Osicala', 'municipio_id' => 42, 'codigo' => '15'],
            ['id' => 234, 'nombre' => 'Perquín', 'municipio_id' => 41, 'codigo' => '16'],
            ['id' => 235, 'nombre' => 'San Carlos', 'municipio_id' => 42, 'codigo' => '17'],
            ['id' => 236, 'nombre' => 'San Fernando', 'municipio_id' => 41, 'codigo' => '18'],
            ['id' => 237, 'nombre' => 'San Francisco Gotera', 'municipio_id' => 42, 'codigo' => '19'],
            ['id' => 238, 'nombre' => 'San Isidro', 'municipio_id' => 41, 'codigo' => '20'],
            ['id' => 239, 'nombre' => 'San Simón', 'municipio_id' => 42, 'codigo' => '21'],
            ['id' => 240, 'nombre' => 'Sensembra', 'municipio_id' => 42, 'codigo' => '22'],
            ['id' => 241, 'nombre' => 'Sociedad', 'municipio_id' => 42, 'codigo' => '23'],
            ['id' => 242, 'nombre' => 'Torola', 'municipio_id' => 41, 'codigo' => '24'],
            ['id' => 243, 'nombre' => 'Yamabal', 'municipio_id' => 42, 'codigo' => '25'],
            ['id' => 244, 'nombre' => 'Yoloaiquín', 'municipio_id' => 42, 'codigo' => '26'],
            ['id' => 245, 'nombre' => 'Anamoros', 'municipio_id' => 43, 'codigo' => '01'],
            ['id' => 246, 'nombre' => 'Bolívar', 'municipio_id' => 43, 'codigo' => '02'],
            ['id' => 247, 'nombre' => 'Concepción De Oriente', 'municipio_id' => 43, 'codigo' => '03'],
            ['id' => 248, 'nombre' => 'Conchagua', 'municipio_id' => 44, 'codigo' => '04'],
            ['id' => 249, 'nombre' => 'El Carmen', 'municipio_id' => 44, 'codigo' => '05'],
            ['id' => 250, 'nombre' => 'El Sauce', 'municipio_id' => 43, 'codigo' => '06'],
            ['id' => 251, 'nombre' => 'Intipucá', 'municipio_id' => 44, 'codigo' => '07'],
            ['id' => 252, 'nombre' => 'La Unión', 'municipio_id' => 44, 'codigo' => '08'],
            ['id' => 253, 'nombre' => 'Lislique', 'municipio_id' => 43, 'codigo' => '09'],
            ['id' => 254, 'nombre' => 'Meanguito Del Golfo', 'municipio_id' => 44, 'codigo' => '10'],
            ['id' => 255, 'nombre' => 'Nueva Esparta', 'municipio_id' => 43, 'codigo' => '11'],
            ['id' => 256, 'nombre' => 'Pasaquina', 'municipio_id' => 43, 'codigo' => '12'],
            ['id' => 257, 'nombre' => 'Polorós', 'municipio_id' => 43, 'codigo' => '13'],
            ['id' => 258, 'nombre' => 'San Alejo', 'municipio_id' => 44, 'codigo' => '14'],
            ['id' => 259, 'nombre' => 'San José', 'municipio_id' => 43, 'codigo' => '15'],
            ['id' => 260, 'nombre' => 'Santa Rosa De Lima', 'municipio_id' => 43, 'codigo' => '16'],
            ['id' => 261, 'nombre' => 'Yayantique', 'municipio_id' => 44, 'codigo' => '17'],
            ['id' => 262, 'nombre' => 'Yucuaquín', 'municipio_id' => 44, 'codigo' => '18'],
        ];

        DB::table('distritos')->upsert($distritos, ['id']);
    }
}
