version: '3'
volumes:
  data:
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lofty_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: db_pass2
      MYSQL_INIT_WAIT_TIMEOUT: 28800
      MYSQL_MAX_ALLOWED_PACKET: 256M
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
